### ISSUE TITLE
Account step 2: Make plan details clearer visually

### ISSUE THREAD

**Issue by scottjehl** [WPO-Foundation/webpagetest#2257]
Proposed design 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/214783/183712086-3496f7f5-c623-4d85-be0e-859c5b126471.png">

CSS for the step 2 aside (account css line 755 or so):

```css
.signup-flow-layout aside h3 {
  font-size: 1rem;
  line-height: 1.6875rem;
}
.signup-flow-layout .plan-name {
  font-weight: 400;
  font-size: 1.25rem;
  line-height: 1.6875rem;
}
.signup-flow-layout .wpt-pro-logo {
  margin: 0 0 1em;
}
.signup-flow-layout .wpt-pro-logo {
    background-position: 0 0;
}
.signup-flow-layout .plan-details {
  background: rgba(0,0,0,.2);
  color: #fff;
  padding: 1em;
  border-radius: .6em;
  margin: 1em 0;
}
.signup-flow-layout .plan-details table {
  font-size: .95em;
  width: 100%;
  border-collapse: collapse;
}
.signup-flow-layout .plan-details table th {
  text-align: left;
  padding: .6em 0;
  font-weight: 500;
    border-bottom: 1px solid rgba(255,255,255,.5);
}
.signup-flow-layout .plan-details table td {
  text-align: right;
  padding: .6em 0;
  font-weight: 700;
  border-bottom: 1px solid rgba(255,255,255,.5);
}
```

PHP For that column:

```php
<div class="plan-details">
        <table>
            <?php if( !$is_plan_free ) : ?>
            <tr>
                <th>Pay Plan:</th>
                <td><?= $billing_frequency ?></td>
            </tr>
            <?php endif; ?>
            <tr>
                <th>Runs/mo:</th>
                <td><?= $runs ? $runs : 300; ?></td>                  
            </tr>
            <tr>
                <th>Price:</th>
                <?php if ($is_plan_free) : ?>
                    <td>Free</td>
                <?php else : ?>
                    <?php if ($billing_frequency == "Monthly") : ?>
                        <td>$<?= "{$monthly_price}/mo" ?></td>
                    <?php else : ?>
                        <td><s>$<?= $other_annual ?></s> $<?= "{$annual_price}/yr" ?></td>
                    <?php endif; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div> <!-- /.plan-details -->
```
